# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ecd876e6166b2bf115be84cbe53cbbb9610eeb3385f932b8ef6377a742f84b76117b02e1e271347b141f6df5b99ae4668438001a3c8d6510e1d40571a1ff1011

test:
  secret_key_base: b5eb6abe56c2a8fca1f650cbf32b40eb68c7662e4ba4d8e22c289210898ebad866839529545a5395587c52f7ac37847b4613e4e80bba8a74678fa91cc94faabe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
